# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CabinAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CabinAR
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Starscream', '~> 3.0.2'



  target 'CabinARTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CabinARUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
